### ISSUE TITLE
Add CDN support

### ISSUE THREAD

**Issue by CLCK0622** [subframe7536/maple-font#77]
Excuse me, I'd like to apply your font to my website, and I wonder if it is possible to add a CDN support so that it can be easier and faster to use? Many thanks.

**Comment by plutonium-239** [comment]
Hello, I think they meant it would be easy to use on websites if hosted on a CDN (such as Google fonts, `fontsource`, etc.)
That way, we don't have to host the font files on our server and can rely on the CDN server, while just adding one line of HTML in the `head`. 
(which has other benefits as well, such as CDN servers being distributed across the globe for fast access and non-duplicated downloads when 2 sites request the same file from CDN)

**Comment by plutonium-239** [comment]
You can request `fontsource` to host your font [as described here](https://github.com/fontsource/fontsource#adding-new-fonts)

**Comment by CLCK0622** [comment]
> Hello, I think they meant it would be easy to use on websites if hosted on a CDN (such as Google fonts, `fontsource`, etc.) That way, we don't have to host the font files on our server and can rely on the CDN server, while just adding one line of HTML in the `head`. (which has other benefits as well, such as CDN servers being distributed across the globe for fast access and non-duplicated downloads when 2 sites request the same file from CDN)

Exactly. Thanks for follow-up.

**Comment by plutonium-239** [comment]
Hi @subframe7536, can we expect this?

**Comment by subframe7536** [comment]
> You can request `fontsource` to host your font [as described here](https://github.com/fontsource/fontsource#adding-new-fonts)

Yes, I plan to do it recently.

**Comment by subframe7536** [comment]
https://github.com/fontsource/font-files/pull/90

**Comment by subframe7536** [comment]
Have been merged

**Comment by flawrist** [comment]
Is there non-variable Maple Mono (regular TTF/WOFF2 to work with it in Windows 7) with slashed zero available via JSDelivr CDN? I tried this, but with no success.

``` css
@font-face {
  font-family: "Maple Mono";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url(https://cdn.jsdelivr.net/fontsource/fonts/maple-mono@latest/latin-400-normal.woff2) format(woff2);
}

code {
  font-family: "Maple Mono", monospace;
  font-feature-settings: "zero" 1;
}
```

## Workaround

``` css
@font-face {
   font-family: "ZSFT-443";
   src: url("https://fontsapi.zeoseven.com/443/main.woff2") format("woff2");
   font-style: normal;
   font-weight: 100 900;
   font-display: swap;
}

@font-face {
   font-family: "ZSFT-443";
   src: url("https://fontsapi.zeoseven.com/443/italic.woff2") format("woff2");
   font-style: italic;
   font-weight: 100 900;
   font-display: swap;
}

code {
  font-family: "ZSFT-443", monospace;
  font-feature-settings: "zero" 1;
}
```
